name: Deploy Application to Elastic Beanstalk

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'continuous-integration'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: false
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
#     steps:
#     # Checkout the repository to the GitHub Actions runners
#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Configure AWS Credentials Action For GitHub Actions
#       uses: aws-actions/configure-aws-credentials@v1-node16
#       with:
#         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
#         aws-secret-access-key: ${{ secrets.SECRET_KEY }}
#         aws-region: us-east-1

#     - name: Terraform Init
#       uses: hashicorp/setup-terraform@v3
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#     - name: Terraform Validate
#       uses: hashicorp/setup-terraform@v3
    
#         # Generates an execution plan for Terraform
#     - name: Terraform Plan
#       id: plan
#       if: github.ref != 'refs/heads/main' || github.event_name == 'push'
#       run: |
#         terraform plan -no-color -input=false \
#         -out=TFplan.JSON
#       continue-on-error: false
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#     # - name: Terraform Apply
#     #   uses: hashicorp/terraform-github-actions/apply@v0.4.0
#     #   env:
#     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     #     AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
#     #     AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}





# #     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
# #     - name: Setup Terraform
# #       uses: hashicorp/setup-terraform@v1
# # # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
# #     - name: Terraform Init
# #       id: init
# #       run: terraform init

# #     # Checks that all Terraform configuration files adhere to a canonical format
# #     - name: Terraform Format
# #       id: fmt
# #       run: terraform fmt -check

# #     # Checks that all Terraform configuration files are correctly written
# #     - name: Terraform Validate
# #       id: validate
# #       run: terraform validate -no-color



# #     # - name: Terraform Apply
# #     #   if: github.ref == 'refs/heads/main'
# #     #   run: terraform apply -auto-approve -input=false